import React from 'react'
import './LegalContent.css'

export default function Disclaimer() {
  return (
    <div className="legal-page animate-fade-in">
      <div className="legal-header animate-fade-in-up">
        <h1 className="text-gradient">Disclaimer</h1>
        <p className="text-muted">Last updated: May 16, 2026</p>
      </div>

      <div className="legal-content glass-card animate-fade-in-up stagger-1">
        <section>
          <h2>Financial Disclaimer</h2>
          <p>
            MoneyMentor is an educational and informational tool powered by Artificial Intelligence. The content provided on this website, including but not limited to the outputs of the Health Score, Tax Wizard, and FIRE Planner, is for general information purposes only.
          </p>
          <p>
            <strong>MoneyMentor is not a registered financial advisor, tax consultant, or legal expert.</strong> The information provided does not constitute professional financial advice, investment recommendations, or tax planning services.
          </p>
        </section>

        <section>
          <h2>Accuracy of Information</h2>
          <p>
            While we strive to provide accurate and up-to-date information, the world of finance is constantly changing. Tax laws, investment risks, and market conditions vary and can change rapidly. Our AI models are based on general rules and may not account for every unique individual circumstance.
          </p>
        </section>

        <section>
          <h2>No Guarantees</h2>
          <p>
            Past performance is not indicative of future results. Any financial projections generated by our tools are estimates based on various assumptions and are not guarantees of future outcomes.
          </p>
        </section>

        <section>
          <h2>Third-Party Links</h2>
          <p>
            Our website may contain links to third-party websites. These links are provided for your convenience only. We have no control over the content or practices of these websites and are not responsible for any information or services provided by them.
          </p>
        </section>

        <section>
          <h2>Use at Your Own Risk</h2>
          <p>
            By using MoneyMentor, you acknowledge and agree that any reliance on the information provided is at your own risk. You should always perform your own due diligence and consult with qualified professionals before making any financial decisions.
          </p>
        </section>
      </div>
    </div>
  )
}
