import React from 'react'
import './LegalContent.css'

export default function TermsOfService() {
  return (
    <div className="legal-page animate-fade-in">
      <div className="legal-header animate-fade-in-up">
        <h1 className="text-gradient">Terms of Service</h1>
        <p className="text-muted">Last updated: May 16, 2026</p>
      </div>

      <div className="legal-content glass-card animate-fade-in-up stagger-1">
        <section>
          <h2>1. Agreement to Terms</h2>
          <p>
            By accessing or using MoneyMentor, you agree to be bound by these Terms of Service. If you do not agree to all of these terms, do not use our services.
          </p>
        </section>

        <section>
          <h2>2. Description of Service</h2>
          <p>
            MoneyMentor provides AI-powered financial planning tools and educational content. Our services are intended for informational purposes only and do not constitute professional financial, tax, or legal advice.
          </p>
        </section>

        <section>
          <h2>3. No Financial Advice</h2>
          <p>
            The insights and recommendations generated by our AI system are based on mathematical models and general financial principles. You should consult with a qualified financial advisor before making any significant financial decisions. We are not responsible for any financial losses incurred based on the use of our tools.
          </p>
        </section>

        <section>
          <h2>4. User Responsibilities</h2>
          <p>
            You are responsible for providing accurate and complete information when using our tools. You agree not to use our services for any unlawful purpose or in any way that could damage or disable the service.
          </p>
        </section>

        <section>
          <h2>5. Intellectual Property</h2>
          <p>
            All content on MoneyMentor, including text, graphics, logos, and software, is the property of MoneyMentor or its licensors and is protected by copyright and other intellectual property laws.
          </p>
        </section>

        <section>
          <h2>6. Limitation of Liability</h2>
          <p>
            In no event shall MoneyMentor be liable for any indirect, incidental, special, or consequential damages arising out of or in connection with your use of the service.
          </p>
        </section>

        <section>
          <h2>7. Changes to Terms</h2>
          <p>
            We reserve the right to modify these Terms of Service at any time. We will notify you of any changes by posting the new terms on this page.
          </p>
        </section>
      </div>
    </div>
  )
}
